{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gokit-gorilla-restsvc-chart.name" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gokit-gorilla-restsvc-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      {{- range .paths }}
      - path: {{ .Values.ingress.paths.path}}
        pathType: {{ .Values.ingress.paths.pathType}}
        backend:
          serviceName: {{ .Values.ingress.paths.backend.serviceName }}
          servicePort: {{ .Values.ingress.paths.backend.servicePort }}
      {{- end }}
  {{- end }}
