apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmk8s-gokit-gorilla-restsvc.fullname" . }}
  labels:
    {{- include "helmk8s-gokit-gorilla-restsvc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmk8s-gokit-gorilla-restsvc.selectorLabels" . | nindent 4 }}
