# HPA
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gokit-gorillakit-enginesvc-hpa
  namespace: enginesvc
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gokit-gorillakit-enginesvc
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80

--- 
# VPA
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: gokit-gorillakit-enginesvc-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: gokit-gorillakit-enginesvc-vpa
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 250m
        memory: 250Mi
      maxAllowed:
        cpu: 1
        memory: 500Mi
      controlledResources: ["cpu", "memory"]