name: CI Container Scan Image Workflow

permissions:
  contents: read
  packages: write
  id-token: write 
  security-events: write

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]


jobs:

    build:
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      runs-on: ubuntu-latest

      steps:
        - name: Check Out
          uses: actions/checkout@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}


        - name: Extract Image Metadata (Tags) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: isgogolgo13/cncf-k8s-kubevela


        - name: Build Image
          uses: docker/build-push-action@v2
          with:
            tags: ${{ steps.meta.outputs.tags }}
            file: ./Dockerfile


        - name: CVE Scan Image
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'docker.io/isgogolgo13/gokit-gorilla-enginesvc:main'
            format: 'table'
            exit-code: '0'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'UNKNOWN,LOW,HIGH,CRITICAL'


        - name: Push Image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}